/**
 * TS migration emitter (plan §8). Emits a hand-mergeable module exporting the
 * migration id and its up/down operation lists.
 */
import type { MigrationOperation } from '@ormit/core';

export interface EmittedMigration {
  readonly id: string;
  readonly filename: string;
  readonly source: string;
}

/** `20260101120000_add_users` style id from a timestamp + name. */
export function migrationId(name: string, at: Date = new Date()): string {
  const stamp = at.toISOString().replace(/[-:T]/g, '').slice(0, 14);
  const slug = name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
  return `${stamp}_${slug}`;
}

export function emitMigration(
  name: string,
  up: readonly MigrationOperation[],
  down: readonly MigrationOperation[],
  at: Date = new Date(),
): EmittedMigration {
  const id = migrationId(name, at);
  const source = `// Auto-generated by Ormit — safe to edit, but keep up/down in sync.
import type { MigrationOperation } from '@ormit/core';

export const id = ${JSON.stringify(id)};
export const up: MigrationOperation[] = ${JSON.stringify(up, null, 2)};
export const down: MigrationOperation[] = ${JSON.stringify(down, null, 2)};
`;
  return { id, filename: `${id}.ts`, source };
}
