// Auto-generated by Ormit — safe to edit, but keep up/down in sync.
import type { MigrationOperation } from '@ormit/core';

export const id = "20260722183747_add_user_bio";
export const up: MigrationOperation[] = [
  {
    "kind": "addColumn",
    "table": "users",
    "column": {
      "name": "bio",
      "type": "unknown",
      "nullable": true,
      "maxLength": null,
      "defaultValue": null,
      "defaultValueSql": null
    }
  }
];
export const down: MigrationOperation[] = [
  {
    "kind": "dropColumn",
    "table": "users",
    "column": "bio"
  }
];
