// Auto-generated by Ormit — safe to edit, but keep up/down in sync.
import type { MigrationOperation } from '@ormit/core';

export const id = "20260722183746_init";
export const up: MigrationOperation[] = [
  {
    "kind": "createTable",
    "table": "posts",
    "schema": null,
    "columns": [
      {
        "name": "authorId",
        "type": "number",
        "nullable": false,
        "maxLength": null,
        "defaultValue": null,
        "defaultValueSql": null
      },
      {
        "name": "body",
        "type": "unknown",
        "nullable": false,
        "maxLength": null,
        "defaultValue": null,
        "defaultValueSql": null
      },
      {
        "name": "createdAt",
        "type": "Date",
        "nullable": false,
        "maxLength": null,
        "defaultValue": null,
        "defaultValueSql": "CURRENT_TIMESTAMP"
      },
      {
        "name": "id",
        "type": "unknown",
        "nullable": false,
        "maxLength": null,
        "defaultValue": null,
        "defaultValueSql": null
      },
      {
        "name": "title",
        "type": "string",
        "nullable": false,
        "maxLength": 200,
        "defaultValue": null,
        "defaultValueSql": null
      }
    ],
    "primaryKey": [
      "id"
    ]
  },
  {
    "kind": "createTable",
    "table": "users",
    "schema": null,
    "columns": [
      {
        "name": "email",
        "type": "string",
        "nullable": false,
        "maxLength": 200,
        "defaultValue": null,
        "defaultValueSql": null
      },
      {
        "name": "id",
        "type": "unknown",
        "nullable": false,
        "maxLength": null,
        "defaultValue": null,
        "defaultValueSql": null
      },
      {
        "name": "name",
        "type": "string",
        "nullable": false,
        "maxLength": 120,
        "defaultValue": null,
        "defaultValueSql": null
      }
    ],
    "primaryKey": [
      "id"
    ]
  },
  {
    "kind": "createIndex",
    "table": "users",
    "name": "ix_users_email",
    "columns": [
      "email"
    ],
    "unique": true
  }
];
export const down: MigrationOperation[] = [
  {
    "kind": "dropTable",
    "table": "posts",
    "schema": null
  },
  {
    "kind": "dropTable",
    "table": "users",
    "schema": null
  }
];
